### ISSUE TITLE
Asciinema will purge the screencast 'soon'

### ISSUE THREAD

**Issue by rdonkin** [DannyFeliz/star-diff#7]
See https://asciinema.org/a/mCVQf8MgExBspKcKxqLHIyX3p for warning from Asciinema.

Star-diff is nice, thanks for writing it!

**Comment by DannyFeliz** [comment]
Thank you very much for notifying this @rdonkin 👍 

I claimed the recording, now is linked to my account.

I'm glad you liked 🎉
